name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image and container
      run: docker compose up -d --build
    - name: Make migrations
      run: docker-compose exec web python manage.py migrate
    - name: Run test
      run: docker-compose exec web python manage.py test
