name: Book Store CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Make Environment
      run: touch .env
    - name: Get Environment
      run: echo DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }} > .env && cat .env
    - name: Build the Docker image and container
      run: docker compose up -d --build
    - name: Run test
      run: docker compose exec web python manage.py test
