name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  health-check-job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Cache dependency 
      uses: actions/cache@v3 
      with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
    - name: Set up Python environment
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Check Python version 
      run: python --version
    - name: Install requirements 
      run: pip install -r requirements.txt
    - name: Run Migrations
      run: python manage.py migrate
    - name: Run Test
      run: python manage.py test
